---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: funcatron-frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: funcatron-frontend
    spec:
      containers:
        - name: frontend
          resources:
            requests:
              cpu: 0.4
              memory: 256Mi
          #nodeSelector:
          #  role: slave-public
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
          image: funcatron/frontend:latest
